version: '1'

services:
  testauth:
    build: .
    ports:
      - "5000:5000"
    environment:
      - client_id=testauth
      - client_secret=testauth
      - server_metadata_url=https://idppreprod.regionsormland.se/testauth/.well-known/openid-configuration
    restart: unless-stopped